---
- name: CREATE ARM Deployment PLAYBOOK
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    # Variables 'resgrp' and 'location' need to be provided at command line with arg --extra-vars
    templateLink: 'https://raw.githubusercontent.com/nitinpokharna/nitinpokharna/master/azuredeploy.json'
    ParamsLink: 'https://raw.githubusercontent.com/nitinpokharna/nitinpokharna/master/azuredeploy.parameters.json'
  tasks:
  - name: Deploy ARM template
    azure_rm_deployment:
        state: present
        resource_group_name: 'nitinmlwork'
        # location seems to be not optional
        location: 'West Europe'
        template_link: '{{ templateLink }}'
        parameters_link: '{{ ParamsLink }}'
